ik_solver:
  - package: "bt_executer_examples"
    config: "config/ik_solver_config.yaml"
    namespace: "comau_ik_solver"

comau_ik_solver:
  type: ik_solver/Comau_NJ_220_27_IkSolver
  base_frame: comau_base_link # base frame of the chain
  flange_frame: comau_flange # end frame of the chain

  tool_frame: comau_flange # destination frame of the IK (it should be rigid attached to flange_frame)
  desired_solutions: 32 # number of desired solution
  joint_names:
  - comau_joint_1
  - comau_joint_2
  - comau_joint_3
  - comau_joint_4
  - comau_joint_5
  - comau_joint_6